# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
plugins: [jekyll-paginate]

title: Kaige's blackboard
url: http://kaige.github.io
feed: /atom.xml
author_info: <a href="http://kaigefu.github.io/">kaigefu</a>

myblog:
  gavatar: images/gavatar.jpg
  gpname: KaigeFu
#  linkedin: http://www.linkedin.com/in/taotaoli
  github: https://github.com/kaigefu
  email: mailto:kaige.fu@intel.com
  coverimgs: []
  postbgimg: []

categories: [temp]
